#ifndef SANGUIS_TOOLS_ANIMATIONS_CONST_OPTIONAL_IMAGE_FILE_REF_HPP_INCLUDED
#define SANGUIS_TOOLS_ANIMATIONS_CONST_OPTIONAL_IMAGE_FILE_REF_HPP_INCLUDED

#include <sanguis/tools/animations/const_optional_image_file_ref_fwd.hpp>
#include <fcppt/optional/reference.hpp>

#endif
