// Generated by CoffeeScript 1.9.0
(function() {
  var init;

  init = function() {
    var accel, canvas, ctx, img, mouse_pos, newpos, pos, redraw;
    canvas = document.getElementById('canvas');
    ctx = canvas.getContext('2d');
    img = document.getElementById('backgroundImage');
    mouse_pos = function(event) {
      var rect;
      rect = canvas.getBoundingClientRect();
      return {
        x: event.clientX - rect.left,
        y: event.clientY - rect.top
      };
    };
    accel = document.getElementById('accel');
    console.log(accel.value);
    pos = {
      x: canvas.width / 2,
      y: canvas.height / 2
    };
    newpos = pos;
    redraw = function() {
      var h, w, x, y, _i, _ref, _ref1, _results;
      pos.x += (newpos.x - pos.x) / accel.value;
      pos.y += (newpos.y - pos.y) / accel.value;
      w = canvas.width;
      h = canvas.height;
      _results = [];
      for (x = _i = _ref = pos.x - w, _ref1 = img.width; _ref1 > 0 ? _i <= w : _i >= w; x = _i += _ref1) {
        _results.push((function() {
          var _j, _ref2, _ref3, _results1;
          _results1 = [];
          for (y = _j = _ref2 = pos.y - h, _ref3 = img.height; _ref3 > 0 ? _j <= h : _j >= h; y = _j += _ref3) {
            _results1.push(ctx.drawImage(img, x, y, img.width, img.height));
          }
          return _results1;
        })());
      }
      return _results;
    };
    canvas.addEventListener('mousemove', function(event) {
      return newpos = mouse_pos(event);
    });
    return window.setInterval(redraw, 40);
  };

  window.addEventListener('load', init);

}).call(this);
