#ifndef SANGUIS_CLIENT_DRAW2D_SCENE_STATE_OPTIONAL_SCOPED_UNIQUE_PTR_HPP_INCLUDED
#define SANGUIS_CLIENT_DRAW2D_SCENE_STATE_OPTIONAL_SCOPED_UNIQUE_PTR_HPP_INCLUDED

#include <sanguis/client/draw2d/scene/state/optional_scoped_unique_ptr_fwd.hpp>
#include <fcppt/optional/object_impl.hpp>

#endif
