#ifndef SANGUIS_CLIENT_DRAW2D_ENTITIES_WITH_BUFFS_AURAS_MODEL_PARAMETERS_HPP_INCLUDED
#define SANGUIS_CLIENT_DRAW2D_ENTITIES_WITH_BUFFS_AURAS_MODEL_PARAMETERS_HPP_INCLUDED

#include <sanguis/client/draw2d/entities/with_auras_model_parameters.hpp>
#include <sanguis/client/draw2d/entities/with_buffs_auras_model_parameters_fwd.hpp>
#include <sanguis/client/draw2d/entities/with_buffs_parameters_decl.hpp>


#endif
